name: TypeScript Generator

on:
  schedule:
    - cron: "0 8 * * *"  # Run daily at 4:00 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-snippet:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper git operations

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Add random delay
        run: |
          MIN=$((RANDOM % 60))
          echo "Sleeping for $MIN minutes..."
          sleep "${MIN}m"

      - name: Run generator
        run: python update_code.py

      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add learn.ts seen_functions.txt
          git commit -m "chore: append daily snippet" || echo "No changes"
          git push 