name: TypeScript Generator

on:
  schedule:
    - cron: "0 8 * * *"  # Run daily at 4:00 AM UTC
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Required for pushing changes

jobs:
  generate-snippet:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper git operations
          token: ${{ secrets.GITHUB_TOKEN }}  # Use GITHUB_TOKEN for authentication

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Add random delay
        run: |
          MIN=$((RANDOM % 60))
          echo "Sleeping for $MIN minutes..."
          sleep "${MIN}m"

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run generator
        run: python update_code.py

      - name: Commit and push
        run: |
          git add learn.ts seen_functions.txt
          git commit -m "chore: append daily snippet" || echo "No changes"
          git push 